/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#010f1f",
        "on-primary-fixed": "#002112",
        "surface-variant": "#273647",
        "surface-container-high": "#1c2b3c",
        "secondary-container": "#3f465c",
        "on-secondary-container": "#adb4ce",
        "background": "#051424",
        "tertiary": "#c5d4ed",
        "on-surface": "#d4e4fa",
        "on-primary-fixed-variant": "#005233",
        "data-blue": "#3B82F6",
        "primary": "#60eca8",
        "on-surface-variant": "#bbcabe",
        "surface-tint": "#51df9c",
        "tertiary-fixed-dim": "#b9c7e0",
        "inverse-on-surface": "#233143",
        "primary-fixed": "#71fcb6",
        "outline": "#869489",
        "surface-container": "#122131",
        "on-tertiary-container": "#3b495d",
        "error": "#ffb4ab",
        "surface-dim": "#051424",
        "error-container": "#93000a",
        "encryption-gold": "#F59E0B",
        "surface-container-low": "#0d1c2d",
        "on-tertiary-fixed-variant": "#3a485c",
        "primary-container": "#3ecf8e",
        "alert-red": "#EF4444",
        "on-primary-container": "#005434",
        "deep-navy": "#020617",
        "on-secondary": "#283044",
        "tertiary-container": "#aab8d0",
        "on-error": "#690005",
        "surface-container-highest": "#273647",
        "outline-variant": "#3d4a41",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#0d1c2f",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed": "#d5e3fd",
        "secondary": "#bec6e0",
        "on-primary": "#003822",
        "surface": "#051424",
        "on-secondary-fixed-variant": "#3f465c",
        "on-background": "#d4e4fa",
        "on-tertiary": "#233144",
        "inverse-primary": "#006c45",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#51df9c",
        "surface-bright": "#2c3a4c",
        "inverse-surface": "#d4e4fa",
        ink:    { 950:'#051424', 900:'#010f1f', 800:'#0d1c2d', 700:'#1c2b3c', 600:'#273647' },
        signal: { 400:'#60eca8', 500:'#3ecf8e', 600:'#006c45' },
        cipher: { 400:'#60eca8', 500:'#3ecf8e' },
        amber:  { 400:'#F59E0B', 500:'#F59E0B' },
        mist:   { 100:'#d4e4fa', 300:'#bbcabe', 500:'#869489', 700:'#3d4a41' },
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "unit": "4px",
        "gutter-md": "24px",
        "margin-lg": "40px"
      },
      fontFamily: {
        display: ['"Hanken Grotesk"', '"Space Grotesk"', 'sans-serif'],
        body:    ['"Hanken Grotesk"', '"Inter"', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "code-sm": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
      },
      keyframes: {
        pulseline: { '0%,100%':{opacity:0.3},'50%':{opacity:1} },
      },
      animation: {
        pulseline: 'pulseline 2.2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
